def menu_display():
    print("Welcome to the Python AP Chemistry Practice Module")
    print()
    print("Please make your selection:                      #")
    print("##################################################")
    print("#                                                #")
    print("#                                                #")
    print("# 1. Naming Compounds                            #")
    print("# 2. Finding Formulas                            #")
    print("# 3. Balancing Equations                         #")
    print("# 4. Reaction Prediction                         #")
    print("# 5. Stoichiometry                               #")
    print("# 6. Kinetics - Method of initial rates          #")
    print("# 7. Equilibrium*                                #")
    print("# 8. Acid/Base*                                  #")
    print("# 9. Buffer*                                     #")
    print("# 10. Solubility*                                #")
    print("# 11. Thermodynamics*                            #")
    print("# 12. Electrochemistry*                          #")
    print("# 13. Nuclear*                                   #")
    print("# 14. AP Chemistry Review (all topics)*          #")
    print("#                                                #")
    print("##################################################")
    print()
